#!/bin/bash

export PGPASSWORD=$DATABASE_PASSWORD

set -xe

until psql -h $DATABASE_HOST -U $DATABASE_USER -c '\l'; do
  echo >&2 "$(date +%Y%m%dt%H%M%S) Postgres is unavailable - sleeping"
  sleep 1
done
echo >&2 "$(date +%Y%m%dt%H%M%S) Postgres is up - executing command"

pushd /var/www/libretime/airtime_mvc/build/sql/

cat \
  schema.sql \
  sequences.sql \
  views.sql \
  triggers.sql \
  defaultdata.sql \
| psql -h $DATABASE_HOST -U $DATABASE_USER $DATABASE_NAME

popd

echo \
  "INSERT INTO cc_music_dirs (id, directory, type) VALUES (1, '/srv/airtime/stor', 'stor');" \
| psql -h $DATABASE_HOST -U $DATABASE_USER $DATABASE_NAME

mkdir -p /srv/airtime/stor/{imported,organize,problem_files}
