dependencies:
  - name: rabbitmq
    version: 6.8.5
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: postgresql
    version: 6.5.0
    repository: https://kubernetes-charts.storage.googleapis.com
