apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "libretime.fullname" . }}-init
  labels:
    k8s.libretime.org/component: init
    {{- include "libretime.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        k8s.libretime.org/component: init
        {{- include "libretime.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          # command: ["sh", "-c", "chown -R 48:48 /var/log/airtime"]
          env:
            - name: DATABASE_HOST
              value: {{ include "libretime.fullname" . }}-postgresql
            - name: DATABASE_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: DATABASE_NAME
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
          volumeMounts:
            - mountPath: "/srv/airtime/"
              name: storage
          resources:
            {{ toYaml .Values.init.resources | nindent 12 }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "libretime.fullname" . }}
    {{- with .Values.init.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.init.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.init.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
