apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "libretime.fullname" . }}-init
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: init
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libretime.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.libretime.org/component: init
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          # command: ["sh", "-c", "chown -R 48:48 /var/log/airtime"]
          env:
            - name: DATABASE_HOST
              value: {{ include "libretime.fullname" . }}-postgresql
            - name: DATABASE_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
            - name: DATABASE_NAME
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
          volumeMounts:
            - mountPath: "/srv/airtime/"
              name: storage
          resources:
{{ toYaml .Values.init.resources | indent 12 }}
    {{- with .Values.init.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.init.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.init.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "libretime.fullname" . }}
