apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libretime.fullname" . }}-celery
  labels:
    k8s.libretime.org/component: celery
    {{- include "libretime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      k8s.libretime.org/component: celery
      {{- include "libretime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        k8s.libretime.org/component: celery
        {{- include "libretime.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag }}"
          imagePullPolicy: {{ .Values.celery.image.pullPolicy }}
          env:
            - name: RMQ_CONFIG_FILE
              value: "/etc/airtime/airtime.conf"
          volumeMounts:
            - mountPath: "/srv/airtime/"
              name: storage
            - mountPath: "/etc/airtime"
              name: config
              readOnly: true
          resources:
            {{ toYaml .Values.celery.resources | nindent 12 }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "libretime.fullname" . }}
        - name: config
          secret:
            secretName: {{ include "libretime.fullname" . }}
    {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
