apiVersion: v1
kind: Service
metadata:
  name: {{ include "libretime.fullname" . }}-icecast
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: icecast
spec:
  type: {{ .Values.icecast.service.type }}
  ports:
    - port: {{ .Values.icecast.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    k8s.libretime.org/component: icecast
