apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libretime.fullname" . }}-icecast
  labels:
    k8s.libretime.org/component: icecast
    {{- include "libretime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.icecast.replicaCount }}
  selector:
    matchLabels:
      k8s.libretime.org/component: icecast
      {{- include "libretime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        k8s.libretime.org/component: icecast
        {{- include "libretime.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.icecast.image.repository }}:{{ .Values.icecast.image.tag }}"
          imagePullPolicy: {{ .Values.icecast.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{ toYaml .Values.icecast.resources | nindent 12 }}
    {{- with .Values.icecast.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.icecast.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.icecast.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
