apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libretime.fullname" . }}-icecast
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: icecast
spec:
  replicas: {{ .Values.icecast.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libretime.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      k8s.libretime.org/component: icecast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libretime.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.libretime.org/component: icecast
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.icecast.image.repository }}:{{ .Values.icecast.image.tag }}"
          imagePullPolicy: {{ .Values.icecast.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{ toYaml .Values.icecast.resources | nindent 12 }}
    {{- with .Values.icecast.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.icecast.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.icecast.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
