apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "libretime.fullname" . }}
  labels:
    k8s.libretime.org/component: storage
    {{- include "libretime.labels" . | nindent 4 }}
spec:
 {{- if .Values.storage.storageClassName -}}
 storageClassName: {{ .Values.storage.storageClassName | quote }}
 {{- end }}
 accessModes:
    - {{ .Values.storage.accessMode }}
 resources:
   requests:
     storage: {{ .Values.storage.capacity }}
