apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libretime.fullname" . }}-pypo
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: pypo
spec:
  replicas: {{ .Values.pypo.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libretime.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      k8s.libretime.org/component: pypo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libretime.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.libretime.org/component: pypo
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-chown
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          command: ["sh", "-c", "mkdir /var/log/airtime/pypo; chown -R 998:996 /var/log/airtime"]
          volumeMounts:
            - mountPath: "/var/log/airtime/"
              name: logs
      containers:
        - name: {{ .Chart.Name }}-playout
          image: "{{ .Values.playout.image.repository }}:{{ .Values.playout.image.tag }}"
          imagePullPolicy: {{ .Values.playout.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/var/tmp/airtime/pypo/cache/"
              name: cache
            - mountPath: "/etc/airtime"
              name: config
              readOnly: true
            - mountPath: "/var/log/airtime/"
              name: logs
          resources:
            {{ toYaml .Values.playout.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-liquidsoap
          image: "{{ .Values.liquidsoap.image.repository }}:{{ .Values.liquidsoap.image.tag }}"
          imagePullPolicy: {{ .Values.liquidsoap.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/var/tmp/airtime/pypo/cache/"
              name: cache
            - mountPath: "/etc/airtime"
              name: config
              readOnly: true
          resources:
            {{ toYaml .Values.liquidsoap.resources | nindent 12 }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: config
          secret:
            secretName: {{ include "libretime.fullname" . }}
            items:
              - key: airtime.conf
                path: airtime.conf
        - name: logs
          emptyDir: {}
    {{- with .Values.pypo.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pypo.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pypo.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
