apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libretime.fullname" . }}-rabbitmq-load-definition
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: rabbitmq
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "{{ .Values.rabbitmq.rabbitmq.username }}",
          "password": "{{ .Values.rabbitmq.rabbitmq.password }}",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "user": "{{ .Values.rabbitmq.rabbitmq.username }}",
          "vhost": "/libretime",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "vhosts": [
        {
          "name": "/libretime"
        }
      ]
    }
