apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libretime.fullname" . }}-rabbitmq-load-definition
  labels:
    k8s.libretime.org/component: rabbitmq
    {{- include "libretime.labels" . | nindent 4 }}
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "{{ .Values.rabbitmq.rabbitmq.username }}",
          "password": "{{ .Values.rabbitmq.rabbitmq.password }}",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "user": "{{ .Values.rabbitmq.rabbitmq.username }}",
          "vhost": "/libretime",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "vhosts": [
        {
          "name": "/libretime"
        }
      ]
    }
