{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "libretime.fullname" . -}}
{{- $ingressPath := .Values.web.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-web
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: web
{{- with .Values.web.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.web.ingress.tls }}
  tls:
  {{- range .Values.web.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.web.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
