apiVersion: v1
kind: Service
metadata:
  name: {{ include "libretime.fullname" . }}-web
  labels:
    k8s.libretime.org/component: web
    {{- include "libretime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    k8s.libretime.org/component: web
    {{- include "libretime.selectorLabels" . | nindent 4 }}
