apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libretime.fullname" . }}-web
  labels:
    k8s.libretime.org/component: web
    {{- include "libretime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      k8s.libretime.org/component: web
      {{- include "libretime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "libretime.selectorLabels" . | nindent 8 }}
        k8s.libretime.org/component: web
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-chown-logs
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          command: ["sh", "-c", "chown -R 48:48 /var/log/airtime"]
          volumeMounts:
            - mountPath: "/var/log/airtime/"
              name: logs
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /images/airtime_logo.png
              port: http
          readinessProbe:
            httpGet:
              path: /images/airtime_logo.png
              port: http
          volumeMounts:
            - mountPath: "/srv/airtime/"
              name: storage
            - mountPath: "/etc/airtime"
              name: config
              readOnly: true
            - mountPath: "/var/log/airtime/"
              name: logs
          resources:
            {{ toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "libretime.fullname" . }}
        - name: config
          secret:
            secretName: {{ include "libretime.fullname" . }}
        - name: logs
          emptyDir: {}
    {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
