apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "libretime.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "libretime.name" . }}
    helm.sh/chart: {{ include "libretime.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.libretime.org/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "libretime.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      k8s.libretime.org/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "libretime.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.libretime.org/component: web
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-chown-logs
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          command: ["sh", "-c", "chown -R 48:48 /var/log/airtime"]
          volumeMounts:
            - mountPath: "/var/log/airtime/"
              name: logs
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: "/srv/airtime/"
              name: storage
            - mountPath: "/etc/airtime"
              name: config
              readOnly: true
            - mountPath: "/var/log/airtime/"
              name: logs
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
    {{- with .Values.web.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "libretime.fullname" . }}
        - name: config
          secret:
            secretName: {{ include "libretime.fullname" . }}
        - name: logs
          emptyDir: {}
